tasks:
  - before: rm -rf dist
    init: |
      npm ci
      cp .env.example .env
      npm run build
      npm run typeorm migration:run
      npm run fixtures
    command: npm run start:dev

image:
  file: .gitpod.Dockerfile

ports:
  - port: 5000
    onOpen: open-preview
